// Sam Black's Commander Cube — 817 cards
// Source: cubecobra.com/cube/list/38rph
// With the confirmed LotR replacements from our previous session applied:
// Gandalf the White -> Vedalken Orrery + Strionic Resonator
// Radagast -> Momir Vig, Simic Visionary
// Samwise the Stouthearted -> Shepherd of the Flock
// Faramir -> Palace Jailer + Court of Grace
// Samwise Gamgee -> Trostani Discordant + Idol of Endurance
// Aragorn -> Keeper of Keys
// Éomer -> Skyline Despot
// Lembas -> Mind Stone
// Palantír -> Coercive Portal

const SAM_BLACK_CUBE = [
"Benevolent Bodyguard","Giant Killer","Giver of Runes","Mother of Runes","Soul Warden","Soul's Attendant","Yoshimaru, Ever Faithful","Auriok Champion",
"Lion Sash","Luminarch Aspirant","Phelia, Exuberant Shepherd","Regal Bunnicorn","Samwise the Stouthearted","Selfless Spirit","Spirited Companion","Wall of Mourning",
"Wall of Omens","Adeline, Resplendent Cathar","Aven Interrupter","Claim Jumper","Delney, Streetwise Lookout","Enduring Innocence","Flickerwisp","Guardian of Ghirapur",
"Loran of the Third Path","Mirror Entity","Skyclave Apparition","Welcoming Vampire","Elesh Norn","Felidar Guardian","Loran, Disciple of History","Mondrak, Glory Dominus",
"Restoration Angel","Serra Paragon","Wall of Reverence","Witch Enchanter","Abdel Adrian, Gorion's Ward","Angel of Sanctions","Archangel of Thune","Gandalf the White",
"Karmic Guide","Reveillark","Solitude","Archon of Coronation","Sun Titan","Yosei, the Morning Star","Angel of Serenity","Elesh Norn, Grand Cenobite",
"Emeria Shepherd","Luminate Primordial","Serra's Emissary","Elspeth, Sun's Champion","Ephemerate","Final Showdown","Swords to Plowshares","Contraband Livestock",
"Heliod's Intervention","Reprieve","Call the Coppercoats","Eerie Interlude","Stroke of Midnight","Congregate","Cosmic Intervention","White Sun's Twilight",
"Council's Judgment","Dismantling Wave","Sevinne's Reclamation","Starnheim Unleashed","Cleansing Nova","Hallowed Burial","Rout","Season of the Burrow",
"Sunfall","Tragic Arrogance","Akroma's Vengeance","Austere Command","Farewell","Hour of Revelation","Emeria's Call","Vanquish the Horde",
"Glimmer Lens","Staff of the Storyteller","Authority of the Consuls","Legion's Landing","Blind Obedience","Seal of Cleansing","Veteran Soldier","Caretaker's Talent",
"Far Traveler","Grasp of Fate","Tocasia's Welcome","Anointed Procession","Court of Ardenvale","Parallax Wave","Teleportation Circle","Cathars' Crusade",
"Divine Visitation","Elspeth Conquers Death","Virtue of Loyalty","Legion Loyalty","Faerie Seer","Mockingbird","Siren Stormtamer","Esior, Wardwing Familiar",
"Faerie Mastermind","Fblthp, the Lost","Fear of Isolation","Gilded Drake","Jacob Hauken, Inspector","Ledger Shredder","Phantasmal Image","Pollywog Prodigy",
"Stratus Dancer","The Reality Chip","Thieving Skydiver","Aboleth Spawn","Aether Channeler","Dreamtide Whale","Forensic Gadgeteer","Amphin Mutineer",
"Kheru Spellsnatcher","Phyrexian Metamorph","Sakashima of a Thousand Faces","Sakashima's Student","Thassa, Deep-Dwelling","Tradewind Rider","Venser, Shaper Savant","Whirler Rogue",
"Wonder","Body Double","Chromeshell Crab","Mulldrifter","Vesuvan Shapeshifter","All-Seeing Arbiter","Marang River Regent","Sakashima's Protege",
"Diluvian Primordial","Hullbreaker Horror","Nezahal, Primal Tide","Scholar of the Lost Trove","Thought Monitor","Pact of Negation","An Offer You Can't Refuse","Chain of Vapor",
"Consider","Into the Flood Maw","Occult Epiphany","Opt","Pongify","Rapid Hybridization","Stubborn Denial","Suspend",
"Swan Song","Three Steps Ahead","Arcane Denial","Counterspell","Mystic Reflection","Narset's Reversal","Remand","Resculpt",
"Blue Sun's Zenith","Dream Fracture","Force of Negation","Cryptic Command","Transcendent Message","Gale's Redirection","Spell Swindle","Spelljack",
"Sublime Epiphany","Commit // Memory","Dig Through Time","Hard Evidence","Ponder","Preordain","Serum Visions","Blue Sun's Twilight",
"Finale of Revelation","Clear the Mind","Timetwister","Witness the Future","Echo of Eons","Season of Weaving","Time Spiral","Imposter Mech",
"Midnight Clock","Machine God's Effigy","Seal of Removal","Stormchaser's Talent","Clan Crafter","Amphibian Downpour","Equilibrium","Fall from Favor",
"Court of Vantress","Leyline of Anticipation","The Bath Song","Treachery","Virtue of Knowledge","Shark Typhoon","Mind's Dilation","Invasion of Segovia",
"Carrion Feeder","Cryptbreaker","Tinybones, the Pickpocket","Viscera Seer","Accursed Marauder","Blood Artist","Bloodghast","Bloodthrone Vampire",
"Dogged Detective","Guildsworn Prowler","Jadar, Ghoulcaller of Nephalia","Marionette Apprentice","Priest of Forgotten Gods","Vraan, Executioner Thane","Zulaport Cutthroat","Braids, Arisen Nightmare",
"Coffin Queen","Fain, the Broker","Gix, Yawgmoth Praetor","Lord Skitter, Sewer King","Midnight Reaper","Morbid Opportunist","Murderous Rider","Ophiomancer",
"Pawn of Ulamog","Plaguecrafter","Skullport Merchant","Warren Soultrader","Woe Strider","Yahenni, Undying Partisan","Body Launderer","Corpse Augur",
"Crypt Ghast","Disciple of Bolas","Gisa, Glorious Resurrector","Gonti, Lord of Luxury","Hazel's Brewmaster","Rankle, Master of Pranks","Ravenous Chupacabra","Shadowheart, Dark Justiciar",
"Twilight Prophet","Vindictive Lich","Yawgmoth, Thran Physician","Custodi Lich","Gray Merchant of Asphodel","Massacre Girl","Overlord of the Balemurk","Puppeteer Clique",
"Sheoldred","Young Necromancer","Grave Titan","Harvester of Souls","Kokusho, the Evening Star","Marionette Master","Massacre Wurm","Noxious Gearhulk",
"Vein Ripper","Butcher of Malakir","Sepulchral Primordial","Archon of Cruelty","Tevesh Szat, Doom of Fools","Liliana, Dreadhorde General","Erebos's Intervention","Deadly Dispute",
"Go for the Throat","Wake the Dead","Corpse Dance","Saw in Half","Soul Shatter","Vona's Hunger","Baleful Mastery","Fell the Profane",
"Flare of Malice","Lethal Scheme","Makeshift Mannequin","Price of Fame","Murderous Cut","Overwhelming Remorse","Szat's Will","Thrilling Encore",
"Curtains' Call","Reanimate","Black Sun's Zenith","Agadeem's Awakening","Victimize","Blood for Bones","Extinction Event","Living Death",
"Season of Loss","Decree of Pain","Nihil Spellbomb","Whip of Erebos","Phyrexian Reclamation","Animate Dead","The Meathook Massacre","Agent of the Iron Throne",
"Bastion of Remembrance","Necromancy","Court of Locthwain","Diabolic Servitude","Rograkh, Son of Rohgahh","Dragonmaster Outcast","Goblin Welder","Impulsive Pilferer",
"Unlucky Witness","Dire Fleet Daredevil","Goblin Cratermaker","Grenzo, Havoc Raiser","Loyal Apprentice","Mogg War Marshal","Agitator Ant","Breya's Apprentice",
"Captain Lannery Storm","Dualcaster Mage","Glóin, Dwarf Emissary","Goblin Rabblemaster","Krenko, Tin Street Kingpin","Laelia, the Blade Reforged","Legion Warboss","Magus of the Wheel",
"Patron of the Arts","Plundering Barbarian","Professional Face-Breaker","Seasoned Pyromancer","Toggo, Goblin Weaponsmith","Anger","Captivating Crew","Emberwilde Captain",
"Jaxis, the Troublemaker","Krenko, Mob Boss","Pia and Kiran Nalaar","Redcap Gutter-Dweller","Rekindling Phoenix","Brash Taunter","Frenzied Saddlebrute","Glorybringer",
"Ilharg, the Raze-Boar","Ox of Agonas","Pinnacle Monk","Port Razer","Siege-Gang Commander","Terror of the Peaks","Urabrask, Heretic Praetor","Zealous Conscripts",
"Combustible Gearhulk","Etali, Primal Storm","Inferno Titan","Dargo, the Shipwrecker","Molten Primordial","Stalking Vengeance","Greater Gargadon","Chandra, Torch of Defiance",
"Daretti, Scrap Savant","Great Train Heist","Lightning Bolt","Unholy Heat","Return the Favor","Untimely Malfunction","Arcbond","Chaos Warp",
"Flare of Duplication","Big Score","Act of Aggression","Glimpse of Tomorrow","Subterranean Tremors","Crackle with Power","Shatterskull Smashing","Indomitable Creativity",
"Seize the Spotlight","Wheel of Fortune","Chain Reaction","Mizzix's Mastery","Burn Down the House","Chandra's Ignition","Mass Mutiny","Song-Mad Treachery",
"Jokulhaups","Mob Rule","Star of Extinction","Blasphemous Act","Insurrection","Obliterate","Warp World","Cursed Mirror",
"Embercleave","Bitter Reunion","Goblin Bombardment","Guild Artisan","Spiteful Banditry","Fable of the Mirror-Breaker","Court of Embereth","Flameshadow Conjuring",
"Frenzied Fugue","Sneak Attack","The Akroan War","Rain of Riches","Stolen Strategy","Warstorm Surge","Vicious Shadows","City on Fire",
"Birds of Paradise","Citanul Stalwart","Delighted Halfling","Gilded Goose","Jaspera Sentinel","Sakura-Tribe Scout","Incubation Druid","Satyr Wayfinder",
"Scavenging Ooze","Shigeki, Jukai Visionary","Sylvan Caryatid","Voracious Hydra","Wall of Blossoms","Augur of Autumn","Courser of Kruphix","Dryad of the Ilysian Grove",
"Endurance","Enduring Vitality","Eternal Witness","Jaheira, Friend of the Forest","Managorger Hydra","Rishkar, Peema Renegade","Scute Swarm","Tireless Provisioner",
"Tireless Tracker","Wayward Swordtooth","Beast Whisperer","Druid of Purification","Halana, Kessig Ranger","Howlpack Piper","Oracle of Mul Daya","Radagast the Brown",
"Spike Weaver","Temur Sabertooth","Timeless Witness","Toski, Bearer of Secrets","Yeva, Nature's Herald","Cavalier of Thorns","Deep Forest Hermit","Tendershoot Dryad",
"Bane of Progress","Kodama of the East Tree","Kogla, the Titan Ape","Avenger of Zendikar","Hornet Queen","Regal Force","Titan of Industry","Apex Devastator",
"Woodfall Primus","Vivien Reid","Berserk","Nature's Claim","Tamiyo's Safekeeping","Blessed Respite","Heroic Intervention","Inscription of Abundance",
"Beast Within","Pulse of Murasa","Return of the Wildspeaker","Abundant Harvest","Explore","Gaea's Blessing","Regrowth","Bala Ged Recovery",
"Genesis Wave","Overwhelming Stampede","Seasons Past","Storm the Festival","Last March of the Ents","The Great Aurora","Esika's Chariot","Monster Manual",
"The Great Henge","Abundant Growth","Utopia Sprawl","Wild Growth","Evolutionary Leap","Fertile Ground","Oath of Druids","Seal of Primordium",
"Season of Growth","Up the Beanstalk","Beastmaster Ascension","Cloakwood Hermit","Court of Garenbrig","Elemental Bond","Fight Rigging","Growing Rites of Itlimoc",
"Ulvenwald Mysteries","Elven Chorus","Greater Good","Guardian Project","Parallel Lives","Doubling Season","The Mending of Dominaria","Lurking Predators",
"Virtue of Strength","Zendikar Resurgent","Invasion of Ixalan","Invasion of Shandalar","Hangarback Walker","Stonecoil Serpent","Walking Ballista","Ornithopter of Paradise",
"Scrap Trawler","Stuffy Doll","Wandering Archaic","Duplicant","Oblivion Sower","Steel Hellkite","Wurmcoil Engine","Meteor Golem",
"Myr Battlesphere","Pentavus","Cityscape Leveler","Kozilek, Butcher of Truth","Ulamog, the Ceaseless Hunger","Ulamog, the Infinite Gyre","Karn, Scion of Urza","Ugin, the Spirit Dragon",
"All Is Dust","Everflowing Chalice","Mishra's Bauble","Aether Vial","Animation Module","Basilisk Collar","Bloodforged Battle-Axe","Elixir of Immortality",
"Relic of Progenitus","Shadowspear","Skullclamp","Soul-Guide Lantern","Springleaf Drum","Witch's Oven","Wizard's Rockets","Agatha's Soul Cauldron",
"Alchemist's Vial","Arcane Signet","Blackblade Reforged","Blade of Selves","Bloodthirsty Blade","Coldsteel Heart","Elsewhere Flask","Energy Refractor",
"Fellwar Stone","Golden Egg","Guild Globe","Ichor Wellspring","Idol of Oblivion","Lembas","Lightning Greaves","Liquimetal Torque",
"Prismatic Lens","Prophetic Prism","Smuggler's Copter","Spare Supplies","Star Compass","Swiftfoot Boots","Thought Vessel","Treasure Map",
"Umezawa's Jitte","Ashnod's Altar","Chromatic Lantern","Coalition Relic","Commander's Sphere","Cultivator's Caravan","Heraldic Banner","Hylda's Crown of Winter",
"Inspiring Statuary","Mimic Vat","Oblivion Stone","Palantír of Orthanc","Patriar's Seal","Phyrexian Altar","Rings of Brighthearth","Sculpting Steel",
"Skyclave Relic","The Celestus","Thousand-Year Elixir","Transmogrifying Wand","Worn Powerstone","Bonehoard","Erratic Portal","Firemind Vessel",
"Hedron Archive","Helm of the Host","Nautiloid Ship","Nevinyrral's Disk","Nyx Lotus","Panharmonicon","Smokestack","Stonespeaker Crystal",
"The Hexcore","Trading Post","Alhammarret's Archive","Batterskull","Conjurer's Closet","Gauntlet of Power","Gilded Lotus","Memory Jar",
"Skysovereign, Consul Flagship","The Mightstone and Weakstone","Coveted Jewel","The Immortal Sun","Akroma's Memorial","God-Pharaoh's Gift","Mendicant Core, Guidelight","Niambi, Esteemed Speaker",
"Faramir, Steward of Gondor","Soulherder","Brago, King Eternal","Ephara, God of the Polis","Kykar, Zephyr Awakener","Shorikai, Genesis Engine","Vohar, Vodalian Desecrator","Satoru Umezawa",
"Silas Renn, Seeker Adept","Hostage Taker","Talion, the Kindly Lord","Hidetsugu and Kairi","Nymris, Oona's Trickster","Xanathar, Guild Kingpin","Kroxa, Titan of Death's Hunger","Florian, Voldaren Scion",
"Mayhem Devil","Vial Smasher the Fierce","Xantcha, Sleeper Agent","Kardur, Doomscourge","Prosper, Tome-Bound","Karazikar, the Eye Tyrant","Max, the Daredevil","Meria, Scholar of Antiquity",
"Svella, Ice Shaper","Decimate","Halana and Alena, Partners","Xenagos, God of Revels","Kogla and Yidaro","Dragonlord Atarka","Samwise Gamgee","Dr. John Seward",
"Gluntch, the Bestower","Mike, the Dungeon Master","Selvala, Explorer Returned","Ellivere of the Wild Court","Leinore, Autumn Sovereign","Mirari's Wake","Elas il-Kor, Sadistic Pilgrim","Lotho, Corrupt Shirriff",
"Will the Wise","Breena, the Demagogue","Kambal, Profiteering Mayor","Minthara, Merciless Soul","Shadrix Silverquill","Merciless Eviction","Jhoira, Ageless Innovator","Third Path Iconoclast",
"Baral and Kari Zev","Ludevic, Necro-Alchemist","Jhoira, Weatherlight Captain","Keranos, God of Storms","The Locust God","Ovika, Enigma Goliath","Baba Lysaga, Night Witch","Glissa Sunslayer",
"Grist, the Hunger Tide","Honest Rutstein","Old Rutstein","Pernicious Deed","Meren of Clan Nel Toth","Ikra Shidiqi, the Usurper","Boros Charm","Bruse Tarl, Boorish Herder",
"Osgir, the Reconstructor","Éomer, King of Rohan","Quintorius, Loremaster","Aurelia, the Warleader","Duke Ulder Ravengard","Gisela, Blade of Goldnight","Hydroid Krasis","Lonis, Cryptozoologist",
"The Goose Mother","Edric, Spymaster of Trest","Inga and Esika","Kydele, Chosen of Kruphix","Imoti, Celebrant of Bounty","Aesi, Tyrant of Gyre Strait","Lagrella, the Magpie","Rigo, Streetwise Mentor",
"Shanna, Purifying Blade","Brenard, Ginger Sculptor","Roon of the Hidden Realm","Aminatou, the Fateshifter","Raffine, Scheming Seer","Sefris of the Hidden Ways","Toluz, Clever Conductor","Yennett, Cryptic Sovereign",
"Marchesa, Dealer of Death","Cormela, Glamour Thief","Marchesa, the Black Rose","Evelyn, the Covetous","Sol'Kanar the Tainted","Gyrus, Waker of Corpses","Henzie "Toolbox" Torre","Slimefoot and Squee",
"Lord Windgrace","Sek'Kuar, Deathkeeper","Atla Palani, Nest Tender","Jetmir, Nexus of Revels","Kitt Kanto, Mayhem Diva","Marisi, Breaker of the Coil","Phabine, Boss's Confidant","Jan Jansen, Chaos Crafter",
"Zurgo Stormrender","Queen Marchesa","Neriv, Crackling Vanguard","Piru, the Volatile","Animar, Soul of Elements","Eshki Dragonclaw","Rashmi and Ragavan","Borborygmos and Fblthp",
"Xyris, the Writhing Storm","Tayam, Luminous Enigma","Thalia and The Gitrog Monster","Ghave, Guru of Spores","Colfenor, the Last Yew","Karador, Ghost Chieftain","Narset, Jeskai Waymaster","Aragorn, King of Gondor",
"Kykar, Wind's Fury","Shiko and Narset, Unified","Shiko, Paragon of the Way","Kotis, Sibsig Champion","Zimone and Dina","Teval, Arbiter of Virtue","The Mimeoplasm","Yarok, the Desecrated",
"Azorius Chancery","Glacial Fortress","Hallowed Fountain","Razortide Bridge","Sea of Clouds","Tundra","Dimir Aqueduct","Drowned Catacomb",
"Mistvault Bridge","Morphic Pool","Underground Sea","Watery Grave","Badlands","Blood Crypt","Dragonskull Summit","Drossforge Bridge",
"Luxury Suite","Rakdos Carnarium","Gruul Turf","Rootbound Crag","Slagwoods Bridge","Spire Garden","Stomping Ground","Taiga",
"Bountiful Promenade","Savannah","Selesnya Sanctuary","Sunpetal Grove","Temple Garden","Thornglint Bridge","Godless Shrine","Goldmire Bridge",
"Isolated Chapel","Orzhov Basilica","Scrubland","Vault of Champions","Izzet Boilerworks","Silverbluff Bridge","Steam Vents","Sulfur Falls",
"Training Center","Volcanic Island","Bayou","Darkmoss Bridge","Golgari Rot Farm","Overgrown Tomb","Undergrowth Stadium","Woodland Cemetery",
"Boros Garrison","Clifftop Retreat","Plateau","Rustvale Bridge","Sacred Foundry","Spectator Seating","Breeding Pool","Hinterland Harbor",
"Rejuvenating Springs","Simic Growth Chamber","Tanglepool Bridge","Tropical Island","Black Dragon Gate","Citadel Gate","Cliffgate","Conduit Pylons",
"Crystal Grotto","Forbidden Orchard","Manor Gate","Path of Ancestry","Sea Gate","Shimmerdrift Vale","Thriving Bluff","Thriving Grove",
"Thriving Heath","Thriving Isle","Thriving Moor"
];

// Mark legendary creatures/planeswalkers as potential commanders
const LEGENDARY_COMMANDERS = new Set([
// Commander status determined dynamically via Scryfall
]);

window.CUBE_DATA = { cards: SAM_BLACK_CUBE, commanders: LEGENDARY_COMMANDERS };
